//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Validation;

namespace Sklad.Module.BusinessObjects.TEST
{
    /// <summary>
    /// Площадки
    /// </summary>
    public partial class Platform : XPLiteObject
    {
        /// <summary>
        /// Идентификатор
        /// </summary>
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }

        /// <summary>
        /// Склад
        /// </summary>
        Sklad fIDsklad;
        [Association(@"PlatformReferencesSklad")]
        [RuleRequiredField("RuleRequiredField for Platform.IDsklad", DefaultContexts.Save)]
        public Sklad IDsklad
        {
            get { return fIDsklad; }
            set { SetPropertyValue<Sklad>(nameof(IDsklad), ref fIDsklad, value); }
        }
           
        /// <summary>
        /// Вес груза
        /// </summary>
        float fcargo;
        [RuleRequiredField("RuleRequiredField for Platform.cargo", DefaultContexts.Save)]
        public float cargo
        {
            get { return fcargo; }
            set { SetPropertyValue<float>(nameof(cargo), ref fcargo, value); }
        }

        /// <summary>
        /// Название
        /// </summary>
        string fName;
        [Size(50)]
        [RuleRequiredField("RuleRequiredField for Platform.Name", DefaultContexts.Save)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }

        /// <summary>
        /// Коллекция пикетов
        /// </summary>
        [Association(@"PicketReferencesPlatform")]
        public XPCollection<Picket> Pickets { get { return GetCollection<Picket>(nameof(Pickets)); } }
        
    }
}
