//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Validation;

namespace Sklad.Module.BusinessObjects.TEST
{

    public partial class Sklad : XPLiteObject
    {
        /// <summary>
        /// Идентификатор
        /// </summary>
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }

        /// <summary>
        /// Название
        /// </summary>
        string fName;
        [RuleRequiredField("RuleRequiredField for Sklad.Name", DefaultContexts.Save)]
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }

        /// <summary>
        /// Коллекция площадок
        /// </summary>
        [Association(@"PlatformReferencesSklad")]
        public XPCollection<Platform> Platforms { get { return GetCollection<Platform>(nameof(Platforms)); } }
    }
}
